{"name": "test_a", "status": "skipped", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <scripts.test_02.TestDependenc object at 0x0000012771B46FD0>\n\n    @pytest.mark.dependency()\n    @pytest.mark.xfail(reason=\"deliberate fail\")\n    def test_a(self):\n>       assert False\nE       assert False\n\ntest_02.py:22: AssertionError"}, "start": 1600157404417, "stop": 1600157404418, "uuid": "af3c7bc9-4711-4086-aa0a-24dd6e644b6f", "historyId": "7d0f5d31578e3c68c6c87c4b2822c883", "fullName": "test_02.TestDependenc#test_a", "labels": [{"name": "tag", "value": "dependency"}, {"name": "parentSuite"}, {"name": "suite", "value": "test_02"}, {"name": "subSuite", "value": "TestDependenc"}, {"name": "host", "value": "DEATH-NOTE00"}, {"name": "thread", "value": "116-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_02"}]}